// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwdpsjveirjqevdcxrlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZHBzanZlaXJqcWV2ZGN4cmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MTkxNDAsImV4cCI6MjA4NTE5NTE0MH0.HiBs6oKmUcrvPrtr7B2HasrT_gjZvrBKnf7f4o_Jjf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});